name: todo-app
services:
  next:
    build:
      context: ${NEXT_SRC_DIR}
      dockerfile: Dockerfile.dev
    container_name: next
    env_file:
      - .env
    ports:
      - "${NEXT_HOST_PORT:-3000}:3000"
    volumes:
      - ${NEXT_SRC_DIR}:/workdir

  express:
    build:
      context: ${EXPRESS_SERVER_SRC_DIR}
      dockerfile: Dockerfile.dev
    container_name: express
    env_file:
      - .env
    ports:
      - "${EXPRESS_SERVER_PORT:-3001}:3000"
      - "${EXPRESS_DEBUG_SERVER_PORT:-9229}:9229"
    volumes:
      - ${EXPRESS_SERVER_SRC_DIR}:/workdir

  postgresql:
    build:
      context: dockerfiles/postgresql
      dockerfile: Dockerfile.dev
    container_name: postgresql
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT:-15432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    ports:
      - "${MAIL_UI_PORT:-8025}:8025"
      - "${MAIL_SMTP_PORT:-1025}:1025"
    volumes:
      - mailhog_data:/home/mailhog

  minio:
    build:
      context: dockerfiles/minio
      dockerfile: Dockerfile.dev
    container_name: minio
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:
  mailhog_data:
